name: piefly
description: Food delivery app with full features
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.3.0
  google_sign_in: ^6.1.5
  provider: ^6.1.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  fluttertoast: ^8.2.2
  http: ^1.1.0
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.1
  uuid: ^4.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
